### ISSUE TITLE
generate-changelog should handle repos that do not have a starting tag

### ISSUE THREAD

**Issue by jchauncey** [deis/deisrel#49]
`generate-changelog` requires a beginning tag for it to work properly. If this tag does not exist then we drop all commit messages on the floor and we leave out that repo completely. This means that the first release a component would show up in it would not get an entry in the aggregate changelog.

In this case we should take commit 0...HEAD

**Comment by bacongobbler** [comment]
It's just an API-level commit compare. You can just as easily point to the very first commit. The problem is trying to compute that as I don't believe there is a way to say "compare from the first commit" without knowing what the first commit sha actually is. We could hardcoded it I guess since commits are anchors but that isn't easily extendable for introducing new projects to deisrel.

**Comment by jchauncey** [comment]
You should be able to get all of the commits in order. Just take the first
and last and tag that as the new release.

**Comment by jchauncey** [comment]
I don't think we need to do much logic here. Either a repo has the tag or it doesnt. If not then we take the first commit ever and use that sha.

**Comment by mboersma** [comment]
This is a deisrel issue now that should be revisited; also we should nuke the old changelog generator scripts from repos.

**Comment by vdice** [comment]
As the need for this hasn't cropped up for a while and no new repos are forecast to be added to the workflow release train, this issue will be closed.
