### ISSUE TITLE
readme output was incorrect when running deisrel helm-stage

### ISSUE THREAD

**Issue by bacongobbler** [deis/deisrel#85]
For a major release, we were using v2.0.0 as the release name. However, in the README I got

```
# Deis Workflow 2.0.0-v2.0.0
```

As the title. This is probably due to deisrel replacing all instances of `-rc2` with `-v2.0.0`.

**Comment by vdice** [comment]
@bacongobbler: for the `v2.0.0` major release, did you just set both `$WORKFLOW_RELEASE` and `$WORKFLOW_RELEASE_SHORT` to the same `v2.0.0` string?  If so, we can check this equivalence in deisrel and just prevent the logic of replacing `-dev` with `$WORKFLOW_RELEASE_SHORT`.

Alternately, we could tweak deisrel so that the `$WORKFLOW_RELEASE_SHORT` env var is optional... if defined (for a minor release), run the replacement logic, if not defined (for a major release), just remove the `-dev` short version from the base chart being updated.

**Comment by bacongobbler** [comment]
> for the v2.0.0 major release, did you just set both $WORKFLOW_RELEASE and $WORKFLOW_RELEASE_SHORT to the same v2.0.0 string?

yep! :) that would probably be the quick and easy solution.
